### ISSUE TITLE
Add `split-node condition` feature

### ISSUE THREAD

**Issue by lisandrasilva** [runtimeverification/kontrol#139]
In some circumstances, to reason about a proof, it would be helpful to split a node given some condition.
This would provide the user a more interactive way of proving, improving the user experience. 
For instance, if we had node `x` with the following constraint:
```
...
#And { maxUInt8 <Int bool2Word ( maxUInt128 <Int X:Int ) <<Int 7 #Equals true } 
...
```
It would be helpful to split the node into two branches, one where `maxUInt128 <Int X:Int` holds and the other where `notBool maxUInt128 <Int X:Int` holds. This way, we can prove that this branch is unfeasible without reasoning about lemmas. In other cases, it can help to reason about what lemmas are necessary to add. 

The idea is to add the functionality: `kontrol split-node test node condition` that creates two branches: one with the `condition` added to the constraints and other with `notBool condition` added to the constraints.

**Comment by PetarMax** [comment]
This way of doing it, however, appears interactive to me - would clients be able to reproduce the proofs automatically?

An alternative way would be to add a `vm.branch(...)` function perhaps?

**Comment by lisandrasilva** [comment]
That is a very good idea! But I think we can actually have both. 
We can be in the middle of a proof and want to branch some node (`kontrol split-node test node condition`) to check that splitting makes the proof progress (instead of having to change the test and rekompile... ). If we confirm that branching on that condition makes the proof go through, then we could change the test to force the branch to happen, with `vm.branch`.

**Comment by palinatolmach** [comment]
Closed by https://github.com/runtimeverification/kontrol/pull/412.
