### ISSUE TITLE
Add `--smt-tactic <s-expression>` command-line option to `kontrol`

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#168]
Related: https://github.com/runtimeverification/evm-semantics/pull/2086

Now that `smt-tactic` parameter has been added to `kevm_pyk`, we should make ` --smt-tactic <s-expression>` (e.g., `--smt-tactic (check-sat-using smt)`) available as an option in Kontrol.

**Comment by anvacaru** [comment]
I discussed yesterday about this with @geo2a  and he pointed out that the `tactic` argument is grouped with other SMT arguments in the class defined in pyk [here](https://github.com/runtimeverification/pyk/blob/master/src/pyk/cli/args.py#L95). Can we test this to see if the argument is available in kontrol already?

**Comment by palinatolmach** [comment]
Nice, thank you @anvacaru! Sure, I'll do that in the scope of https://github.com/runtimeverification/kontrol/pull/164 later today. In this case, I guess, we should just add it as parameter to `exec_...` function signatures and then pass to `legacy_explore()`.
