### ISSUE TITLE
Add option to exclude `forge build` from `kontrol build` process

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#177]
Currently, `kontrol build` will call `forge build --root .` or the root provided to the `--foundry-project-root` flag. This limits the flexibility to build with `forge` before calling `solc_to_k` on the compiled project.

The fastest way to gain this flexibility would be to have a flag (`--no-forge-biuld` or similar) that, when enabled, would skip the `forge` compilation step and expect an already compiled project.

An alternative to this would be to give `kontrol build` access to `forge build` options such as [`--skip`](https://book.getfoundry.sh/reference/forge/forge-build#build-options).

**Comment by palinatolmach** [comment]
We can

**Comment by palinatolmach** [comment]
https://github.com/runtimeverification/kontrol/pull/184 adds `--no-forge-build` which excludes `forge build` from `kontrol build`.

Support for  `--forge-build-command ` is factored out in a separate backlog item (https://github.com/runtimeverification/kontrol/issues/185).
