### ISSUE TITLE
Contract name clashes when the same contract name is used in multiple libraries.

### ISSUE THREAD

**Issue by spencerhaoxiao** [runtimeverification/kontrol#178]
A foundry project could import multiple projects such as `@openzeppelin-contracts-upgradeable` and `@openzeppelin-contracts` both contains very similar contract names (e.g., [@openzeppelin-contracts-upgradeable/contracts/proxy/utils/Initializable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/tree/0a2cb9a445c365870ed7a8ab461b12acf3e27d63/contracts/proxy/utils/Initializable.sol) and [@openzeppelin-contracts/contracts/proxy/utils/Initializable.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/ecd2ca2cd7cac116f7a37d0e474bbb3d7d5e1c4d/contracts/proxy/utils/Initializable.sol)). Thus, the contract names would clash as we only use the simple file name as contract name internally to check whether they are the same contract.

**Comment by palinatolmach** [comment]
After a discussion with @anvacaru, we realized that the easiest way to achieve that is to automatically add some symbols to contract names in module names to auto-disambiguate contracts with the same name, perhaps similar to how we escape forbidden characters. For example, we can add a `path` field to `Contract` (for example) and add a diff between paths for same-named contracts. The path information is available in the `.json` files located in the `/out` folder, e.g., 
```
"absolutePath": "lib/forge-std/src/StdStorage.sol",
```

That might look something like this:
```
module S2KTestNumber-upgradeable-VERIFICATION
    imports public S2KTestNumber-upgradeable-CONTRACT
```
@nwatson22 what do you think?
