### ISSUE TITLE
Default cheatcode implementation & `uninterpretedCall` cheatcode support

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#192]
We should add a cheatcode (e.g., `uninterpretedCall` or `abstractCall`) that allows specifying a call that is not going to be evaluated by Kontrol and will return a symbolic value instead. We should also add a default implementation of this cheatcode in [Kontrol Cheats](https://github.com/runtimeverification/kontrol-cheatcodes/blob/master/src/KontrolCheats.sol) which will perform the actual code when it's run with Foundry. For that, Kontrol cheatcodes should also be compatible with Foundry (i.e., not break `forge test`).

**Comment by palinatolmach** [comment]
@hjorthjort we've decided not to use this approach to accommodate the External Data request, right?

**Comment by hjorthjort** [comment]
Yes, this won't be the approach we take most likely
