### ISSUE TITLE
Add cheatcode for symbolic `bytes`

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#203]
We should add support for natively generating symbolic `bytes` variables in the form of a `kevm.freshBytes` cheatcode.
Here are some caveats to consider when implementing such cheatcode. Namely, the abi encoding of `bytes` has two cases, depending on whether its length is smaller than 32. For more details, see the [documentation](https://docs.soliditylang.org/en/latest/internals/layout_in_storage.html#bytes-and-string).

A good initial goal would be to have a cheatcode `kevm.freshBytes(length)`, where `length` has to be concrete.

**Comment by palinatolmach** [comment]
Another use case for this cheatcode, as mentioned by `secoalba` on Discord, is generation of symbolic arguments for a function call within the test, which can be used to emulate what's called invariant testing in Foundry (execution of an arbitrary function call and checking a post-condition afterwards):
```
    function check_globalInvariants(bytes4 selector, address caller) public {
        // Execute an arbitrary tx
        bytes memory args = svm.createBytes(1024, 'data');
        vm.prank(caller);
       (bool success,) = address(token).call(abi.encodePacked(selector, args));
        vm.assume(success);

        // Record post-state
        assert(token.totalSupply() == address(token).balance);
    }
```
