### ISSUE TITLE
Test signatures are ignored when checking test versions

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#205]
Identified and reported by ljmanini on Discord.

`foundry.py#proofs_with_test()` returns all proofs that contain the specified test's name in their file, ignoring the test's parameter types, which makes `kontrol` throw error messages suggesting that two versions of a test are available, while, in fact, there's a single version for each of two tests with the same name but different parameters. We should take full function signature into consideration when retrieving the number of available proof versions.

**Comment by palinatolmach** [comment]
Thank you @lmanini for reporting this issue and looking into it! We had a somewhat similar conversation on the format of `kontrol prove --match-test` input (https://github.com/runtimeverification/kontrol/pull/103#issuecomment-1783404744) — at that time, we decided that requesting a user to provide a full signature with parentheses might hurt usability, so we made the help message for `--match-test` more specific, saying that "if a function is overloaded, one can provide a full signature, but otherwise all tests matching the regex or string prefix will be executed". 

Maybe we can add more clarification to the description provided in `kontrol view-kcfg` and the documentation? Do you think that might help? Right now, we are just saying 
```
positional arguments:
  test                  Test to run
```
and 
```
❯ kontrol view-kcfg
usage: kontrol view-kcfg [-h] [--version VERSION] [--verbose] [--debug] [--foundry-project-root FOUNDRY_ROOT] test
kontrol view-kcfg: error: the following arguments are required: test
```

**Comment by yale-vinson** [comment]
@qian-hu is working this one, but we cannot assign to her until she is added to Kontol.

**Comment by yale-vinson** [comment]
In discussion with @qian-hu and @anvacaru we decided that this issue is better dealt with by imporving our documentation as opposed to modifying the codebase. I am going to reassign this to @reekamaharaj and Qian will reach out to bring her up to speed.

One other recommendation from Andrei is to update the "help" message for the "view-kcfg" command ([here](https://github.com/runtimeverification/kontrol/blob/master/src/kontrol/__main__.py#L828)).
