### ISSUE TITLE
Disable integration legacy tests on CI

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#248]
Factored out from https://github.com/runtimeverification/kontrol/pull/75.

The tests on the legacy backend take very long, and we are already testing conformance in KEVM. Any discrepancies between booster and legacy should be upstreamed as KClaim style tests to KEVM.

- Disable legacy tests on CI, for integration, maintain them for profiling (faster).
- Update timeouts.
- Update required status checks.

Note that there is a discrepancy between the output of `test_foundry_auto_abstraction` when the booster is used vs. not. This is mostly due to ensures and requires conditions being ordered differently, also sometimes using the booster seems to add ensures clauses to rule blocks in generated modules w[here](https://github.com/runtimeverification/kontrol/blob/336c92e8c27d2434a038b12b45f6b46aac63d70c/src/tests/integration/test-data/gas-abstraction.expected#L872) the legacy backend does not, for example here.

There are also other tests in [test_foundry_prove.py](https://github.com/runtimeverification/kontrol/pull/75/files#diff-b04daa00a79f80dab79c7ae97738b41df215cea6715fba22514a6fef3efadeaa) that are skipping if the booster is used. I guess in the case of `test_foundry_kompile` it was because there is no need to run it with both.

**Comment by yale-vinson** [comment]
@palinatolmach Is there a reason we can't move this back to Next Up and see if someone from the team can pick it up, or did you want to discuss priority for it in the Standup?

**Comment by palinatolmach** [comment]
According to the previous discussion and [this comment](https://github.com/runtimeverification/kontrol/pull/331#issuecomment-1927271390) by @ehildenb, it was decided to keep legacy tests as long as they fit in 30 minutes, which was achieved by several PRs skipping tests with a longer execution on the legacy backend. 

In view of that, I'll close this issue for now.
