### ISSUE TITLE
kontrol usability issues

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/kontrol#28]
When calling `foundry-view-kcfg` and there are several versions of the same proof, a Python error gets propagated to the top.

It would be a lot nicer if we printed a helpful error message, and listed the available IDs (maybe even with the last time it was run, or some other useful data that can help the user understand which is which).

```
Traceback (most recent call last):
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/bin/.kontrolx-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/__main__.py", line 68, in main
    execute(**vars(args))
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/__main__.py", line 261, in exec_foundry_view_kcfg
    test_id = foundry.get_test_id(test, version)
  File "/nix/store/mhinp1n2lx3bxr0c6iq6f4zh490nw16n-python3.10-kevm-pyk-1.0.301/lib/python3.10/site-packages/kontrolx/foundry.py", line 308, in get_test_id
    raise ValueError(
ValueError: Found 3 matching proofs for PinataTest.testA0(uint256,bool). Use the --version flag to choose one.
```

---

When you get a non-deterministic branch and click it in the TUI, you get a crash:

```
╭────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────╮
│ /nix/store/3q2jq2933abmcn832icdj8fd00pzcxc4-python3.10-pyk-0.1.434/lib/python3.10/site-packages/pyk/k │
│ cfg/tui.py:400 in on_graph_chunk_selected                                                             │
│                                                                                                       │
│   397 │   │   elif message.chunk_id.startswith('ndbranch_'):                                          │
│   398 │   │   │   self._selected_chunk = None                                                         │
│   399 │   │   │   node_source, node_target, *_ = message.chunk_id[8:].split('_')                      │
│ ❱ 400 │   │   │   source_id = int(node_source)                                                        │
│   401 │   │   │   target_id = int(node_target)                                                        │
│   402 │   │   │   ndbranch = single(self._kcfg.ndbranches(source_id=source_id, target_id=targe        │
│   403 │   │   │   self.query_one('#node-view', NodeView).update(ndbranch)                             │
│                                                                                                       │
│ ╭─────────────────────────────────── locals ───────────────────────────────────╮                      │
│ │           _ = ['9']                                                          │                      │
│ │     message = Selected()                                                     │                      │
│ │ node_source = ''                                                             │                      │
│ │ node_target = '8'                                                            │                      │
│ │        self = APRProofViewer(title='APRProofViewer', classes={'-dark-mode'}) │                      │
│ ╰──────────────────────────────────────────────────────────────────────────────╯                      │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: invalid literal for int() with base 10: ''
```

Reproduction:

- clone https://github.com/smart-transaction/test-contract
- checkout branch `hjort`
- ` kevm foundry-kompile --verbose && kevm foundry-prove --test PinataTest.testA0 --smt-timeout 300 --smt-retry-limit 4 --verbose`
- open with `kevm foundry-view-kcfg`
- locate a non-deterministic branch (I see one after node 8).
- click it

---

In the TUI, it should be displayed which test and ID you're looking at. I sometimes want to compare KCFGs in different windows, or leave the computer and come back, so it's nice to have the context of what you're looking at without having to kill the TUI and open it back up.

---

It should be possible to reload the TUI without quitting it and reopening: just hit Shift+R or similar to add new nodes.

--- 

*A Kontrol config*

It is very error prone to keep in mind what command you just kompiled with, which modules are imported, etc.

Instead of requiring the user to always kompile with certain flags, we should offer a configuration file (similar to how foundry does, which lets you set things like number of retries, etc). If you need to try using different flags here and there that can be managed with profiles.

This is also how Foundry does it, so it would be a recognizable pattern for devs.
(As a small bonus, seeing commited `kontrol.toml` files in Solidity git repos would work as good marketing, the same way you see `Dockerfile`s all over and that immediately tells you "oh this team is using Docker".)

So instead of for example

```
kontrolx foundry-kompile --require "aux-lemmas.k" --module-import PinataTest:AUX-LEMMAS --rekompile --with-llvm-library --verbose --regen
```

and then 

```
kontrolx foundry-prove --max-iterations 50 --verbose --no-break-on-calls --test PinataTest.testA0 --max-depth 1000
```

we could have a file `kontrol.toml`:

```toml
[profile.a0]
test = 'PinataTest.testA0'
max-depth = 1000

kompile-require = [ 'aux-lemmas.k' ]
kompile-module-import = [ 'PinataTest:AUX-LEMMAS' ]
kompile-llvm-library = true

prove-max-iterations = 50
prove-break-on-calls = false
```

This would likely reduce errors due to forgetting a certain flags, and improve reproducibility since every engineer should be able to get the same result by just doing 

```
kontrolx foundry-prove --profile a0
```

The best order of priority is probably

1. command-line flags
2. config file
3. defaults

**Comment by hjorthjort** [comment]
TODO: make these separate issues

**Comment by yale-vinson** [comment]
@hjorthjort Is there anything that you need the Kontrol team to do on this Issue at this time, or should we wait for the separate issues referenced above before we move to act on them? We have this listed as "Under Investigation" until that is complete, but please let me and @palinatolmach know if you need more support and we are happy to provide it.

**Comment by hjorthjort** [comment]
I believe a kontrol config may be necessary pretty soon for customer satisfaction, and their ability to reliably reproduce results. But that is a hunch from my side, not something any user has expressed the need for.

**Comment by hjorthjort** [comment]
I've broken this into separate issues.
