### ISSUE TITLE
Publish Docker image on Docker Hub

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/kontrol#31]
Add a workflow `master-push.yml` with a job that builds the image and pushes it to Docker Hub.

The image is tested in: https://github.com/runtimeverification/kontrol/blob/031f4b046726edf8eb05b84cda3379f6d7f1db50/.github/workflows/test-pr.yml#L125

**Comment by F-WRunTime** [comment]
https://hub.docker.com/r/runtimeverificationinc/kontrol
docker push runtimeverificationinc/kontrol:tagname
