### ISSUE TITLE
Add `hevm_success` predicate for compatbility with HEVM

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/kontrol#312]
HEVM fails on `ds-test` and `assert` violations but not on `require` or `revert` statements. This is useful to silence some of the noise coming from overflow errors. Maybe we can add another success predicate, `hevm_success`, for enhanced tool compatibility.

Of course, we need to expose these different success conditions via some cli-argument. For example, we could add an argument `--success` that defaults to `foundry`, but also accepts `hevm`.

**Comment by RaoulSchaffranek** [comment]
Another advantage is that we can use `require` to impose assumptions and `assert` for assertions. Both features are native Solidity and don't require the use of a library. That's also what the native Solidity SMTChecker does. https://docs.soliditylang.org/en/latest/smtchecker.html

**Comment by ehildenb** [comment]
We'll need:

- A new file `hevm.md` which mirrors `foundry.md` with the `hevm_success` predicate: https://github.com/runtimeverification/kontrol/blob/master/src/kontrol/kdist/foundry.md
- A new method like this for generating this predicate: https://github.com/runtimeverification/kontrol/blob/0d35ef478297f7d3004406f5ac951a0e5060d8e1/src/kontrol/foundry.py#L316
- A flag passed through to `_final_cterm` (like `--hevm`) which instead generates the `hevm_success` predicate here: https://github.com/runtimeverification/kontrol/blob/0d35ef478297f7d3004406f5ac951a0e5060d8e1/src/kontrol/prove.py#L660
