### ISSUE TITLE
`vm.prank` flakiness

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#316]
In some cases (unclear the moment what triggers this), `vm.prank()` will not take effect if surrounded by a `vm.expectRevert()`. When attempting to reproduce the example on simple enough code, `vm.prank()` has worked as expected, but not in more convoluted cases such as the Optimism proofs.

**Comment by anvacaru** [comment]
@JuanCoRo  on what version did  this happen? Could it be related to [this](https://github.com/runtimeverification/kontrol/pull/289)?
