### ISSUE TITLE
 Suppress C++ warnings in `kontrol build` output

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/kontrol#328]
When executing the `kontrol build` command, the output is cluttered with numerous C++ warnings. This excessive verbosity obscures the warnings and errors concerning K-compilation, complicating debugging. To enhance clarity and streamline the troubleshooting experience, I suggest suppressing these C++ warnings by default. Instead, they could be made accessible via an opt-in flag. This change would significantly improve the signal-to-noise ratio in the build output, allowing developers to focus on the most relevant issues.

Here is an example log:
[kontrol-build-log.txt](https://github.com/runtimeverification/kontrol/files/14138274/kontrol-build-log.txt)

**Comment by anvacaru** [comment]
Fixed in https://github.com/runtimeverification/evm-semantics/pull/2284, needs to be upstreamed to kontrol with https://github.com/runtimeverification/kontrol/pull/325
