### ISSUE TITLE
Colored output

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/kontrol#332]
It would be nice to color warnings and errors so that they jump to an eye.
Also, we could render [PASSED]/[FAILED] in green and red, respectively.

**Comment by jinxinglim** [comment]
@palinatolmach I think now do we have some form of colored output. Do you think this issue can be closed?

**Comment by palinatolmach** [comment]
Yes, good catch, thanks @jinxinglim!

Closed by https://github.com/runtimeverification/kontrol/pull/656 and https://github.com/runtimeverification/kontrol/pull/642.
