### ISSUE TITLE
Add flag to not create multiple versions of the same proof

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#334]
It is possible that when developing proofs, we don't care about keeping track of multiple versions of the same proof. We could have a flag (e.g., `--single-version`) to automatically delete all existing versions of `Contract.proof` when `kontrol prove Contract.proof --single-version` is executed.

**Comment by palinatolmach** [comment]
Based on the conversation on the standup 02/06, we've decided to
- add this option as a configuration file parameter instead of a CLI flag
- prioritize the completion of https://github.com/runtimeverification/kontrol/issues/333 first

**Comment by palinatolmach** [comment]
Since it was decided to add this option as a configuration file parameter rather than a CLI flag, I'm marking it as blocked on https://github.com/runtimeverification/kontrol/pull/373.

**Comment by palinatolmach** [comment]
Closed in favor of https://github.com/orgs/runtimeverification/projects/23/views/7?pane=issue&itemId=72718013.
