### ISSUE TITLE
`--run-constructor` fails when run on a contract w/o constructor

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#335]
Reported by `secoabla` on Discord.

`kontrol prove --run-constructor` throws the following error 
```
No such file or directory: 'out/proofs/test%SimpleTest.init:None/proof.json'
```
when run on a contract without a constructor, e.g.:
```
contract SimpleTest is Test {
    bool flag = true;
    function test_init() external {
        assert(flag);
    }
}
```

If the contract contains an empty constructor (`constructor() {}`), there's no error. 

We should handle this case gracefully and also ensure that the initialization code (e.g., storage variable initialization) is executed.

**Comment by ehildenb** [comment]
Where the `run-constructor` option is handled: https://github.com/runtimeverification/kontrol/blob/9b4689fd2aa05d1970968a1009b80ad044ecf075/src/kontrol/prove.py#L109

**Comment by palinatolmach** [comment]
The user may want to run the initialization code (which is now executed only if `--run-constructor` is provided) even if there's no explicit constructor defined, since it also includes initialization of variables defined outside of functions, e.g., `flag` in
```
contract PortalTest is Test {
    bool flag = true;
 }
```
Instead of disallowing `--run-constructor` if the contract has no contracts, do you think we could instead not crash on the constructor execution artifacts being non-existent? I'm wondering if we can still run the initialization code in this case.

**Comment by palinatolmach** [comment]
The above is what @RaoulSchaffranek needs for WETH contract verification, so it'd be good to have initialization code executed even in the absence of an explicit `constructor`.
