### ISSUE TITLE
Refactor the module name generation

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/kontrol#337]
**Problem:**
Running a proof which has array types in its definition leads to a crash like 
```sh
 _kore_module = kflatmodule_to_kore(                                                                                                                                                                     
  File "/nix/store/s5dgc4ryqifwbdv9bwjfvxmq8kpr0l76-python3.10-pyk-0.1.613/lib/python3.10/site-packages/pyk/konvert.py", line 424, in kflatmodule_to_kore                                                   
    return Module(name=kflatmodule.name, sentences=(imports + kore_axioms))                                                                                                                                 
  File "/nix/store/s5dgc4ryqifwbdv9bwjfvxmq8kpr0l76-python3.10-pyk-0.1.613/lib/python3.10/site-packages/pyk/kore/syntax.py", line 2138, in __init__                                                         
    name = Id(name)                                                                                                                                                                                         
  File "/nix/store/s5dgc4ryqifwbdv9bwjfvxmq8kpr0l76-python3.10-pyk-0.1.613/lib/python3.10/site-packages/pyk/kore/syntax.py", line 36, in __init__                                                           
    self._check(value)                                                                                                                                                                                      
  File "/nix/store/s5dgc4ryqifwbdv9bwjfvxmq8kpr0l76-python3.10-pyk-0.1.613/lib/python3.10/site-packages/pyk/kore/syntax.py", line 42, in _check                                                             
    raise ValueError(f'Expected identifier, got: {value}')                                                                                                                                                  
ValueError: Expected identifier, got: M-TEST-OPTIMISMPORTALKONTROL-TEST-FINALIZEWITHDRAWALTRANSACTION-PAUSED-UINT256-ADDRESS-ADDRESS-UINT256-UINT256-BYTES-UINT256-BYTES32-BYTES32-BYTES32-BYTES32-BYTES[]-0
-DEPENDS-MODULE 
```
This happens because the brackets `[]` are not accepted in the module name pattern in pyk.
```python
_PATTERN_STR: ClassVar = "[a-zA-Z][0-9a-zA-Z'-]*"
```
In addition, the module name is generated by taking the name of the function and the name of all the arguments, which in case of dynamic arrays, can get pretty big.

A few suggestions:
- module names are generated here: https://github.com/runtimeverification/pyk/blob/272bc8cbcb61b82e1e0ad4fc3669812de213a936/src/pyk/proof/reachability.py#L668
- write a new function in pyk that generates a valid module name given some inputs
- refactor the module name to be `M-CONTRACT-NAME-FUNCTION-NAME-HASH-OF-ARGS` or `M-CONTRACT-NAME-FUNCTION-SELECTOR`, where `FUNCTION-SELECTOR` is the first 4 bytes of the signature hash.

**Comment by ehildenb** [comment]
We should have an upstreamed method in pyk which takes any string as input and produces a valid module name directly, and use that method. It shouldn't be specific to our project, but rather be a generic module-name munger. We can possibly allow passing a prefix/suffix so that we can have some control over the way the module name is generated.

**Comment by palinatolmach** [comment]
I agree that the method should be general and not project-specific, although that means that we probably shouldn't use function selectors (we could probably still hash `proof.id`, but that would hurt readability). At the moment, the module name is just an uppercase `proof.id` with forbidden symbols being escaped:
```
module_name = 'M-' + re.sub(r'[_%().:,]+', '-', self.proof.id.upper())
```
Other than removing illegal characters from `proof.id`, can I ask for your opinion on what could be other rules or logic of module name generation?
