### ISSUE TITLE
Add better documentation to `kontrol prove` flags

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#379]
We should document more thoroughly the rationale behind the flags in `kontrol`, and `kontrol prove` specifically.
Upon running `kontrol prove --help`, this is some of the output that we get:
```
  --always-check-subsumption                                                                                                                                                 
                        Check subsumption even on non-terminal nodes.                                                                                                        
  --no-always-check-subsumption                                                                                                                                              
                        Do not check subsumption on non-terminal nodes.                                                                                                      
  --fast-check-subsumption                                                                                                                                                   
                        Use fast-check on k-cell to determine subsumption.                                                                                                   
  --no-fast-check-subsumption                                                                                                                                                
                        Do not use fast-check on k-cell to determine subsumption.
  --use-booster         Use the booster RPC server instead of kore-rpc.
  --no-use-booster      Do not use the booster RPC server instead of kore-rpc.
  --break-on-calls      Store a node for every EVM call made.
  --no-break-on-calls   Do not store a node for every EVM call made.
  --failure-information
                        Show failure summary for all failing tests
  --no-failure-information
                        Do not show failure summary for failing tests
  --counterexample-information
                        Show models for failing nodes.
  --no-counterexample-information
                        Do not show models for failing nodes.
  --fail-fast           Stop execution on other branches if a failing node is detected.
  --no-fail-fast        Continue execution on other branches if a failing node is detected.
```
It is not immediately clear what is the default and why. We should at least signal in the CLI output which are the default flags (the ones without a `no`) and possibly explain the rationale of the flags more at length in Kontrol's docs.

**Comment by palinatolmach** [comment]
Based on the discussion in Slack, it was decided to 
- add `(default)` to flags that are `true` by default
- make help messages for CLI options more informative

**Comment by palinatolmach** [comment]
As suggested by @PetarMax, options that are meant for expert K users such as `--fast-check-subsumption` (and `--always-check-subsumption`, which will be removed soon) can additionally be marked as `(experimental)`.

**Comment by lisandrasilva** [comment]
My suggestion for this would be to delete the flags that are used by default. For instance, delete the `use-booster` flag and only have:
```
--no-use-booster      Use the kore-rpc server instead of the default booster RPC.
```
In my opinion, having flags for the default values makes the help message more confusing and does not add much value since it is only necessary not to provide any flags to have the same behavior.

**Comment by palinatolmach** [comment]
Please see [this thread on Slack](https://runtimeverification.slack.com/archives/C03NP1UP2KZ/p1708608522505929): the arguments in favor of keeping both options are
- it's standard across many dev tools
- it explicitly describes the behavior of the tool
- it's useful if you have a TOML file turning `--X` off, and you want to override that on the CLI for a specific run

**Comment by lisandrasilva** [comment]
Ahh ok makes sense thank you!

**Comment by lisandrasilva** [comment]
After reading the discussion, I agree that we should have `--X` and `--no-X` flags, especially because of the TOML file functionality. But then, wouldn't it make sense to have both for other flags? For instance, we have the `--break-on-jumpi` flag, but we do not have the `no-break-on-jumpi` flag. If `--break-on-jumpi` is on in the TOML file, there's no way to turn it off in CLI. On the other hand, if we have both `X` and `--no-X` for all of them, it would make the `--help` even more confusing, in my opinion. 
Let me know your thoughts @palinatolmach, @ehildenb.
