### ISSUE TITLE
Add a warning on non-test analysis w/o `foundry_success` checking

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#386]
Related: https://github.com/runtimeverification/kontrol/issues/312

In Kontrol, we only check `foundry_success` predicate (and, therefore, report the test as failing) if the name of the test starts with `test`, `check`, or `prove` (https://github.com/runtimeverification/kontrol/pull/249). Once https://github.com/runtimeverification/kontrol/issues/312 is fixed, we'll be able to also check `hevm_success` predicate.  

However, right now, if the test doesn't start from one of these three prefixes, it is being symbolically explored, but does not get reported as failing even if the test reverts. As reported by @dwightguth, it is confusing and looks like a bug, so we should probably emit a warning that informs the user that the test is _not_ being checked for failures.

**Comment by ehildenb** [comment]
This is intended behavior though for methods without `test_` prefix, so that the user can create a summary to be used in running other tests/functions (via the `--include-summary ...` option). So a warning seems too strong here, maybe some documentation, or an INFO log.
