### ISSUE TITLE
Check if libstdc++-12-dev is a necessary dependency

### ISSUE THREAD

**Issue by ACassimiro** [runtimeverification/kontrol#409]
When trying to build Kontrol and `evm-semantics` from source, errors were triggered in the installation process. This was done in a freshly installed Ubuntu 22.04.3 virtual machine, and the errors are triggered when executing `poetry -C kevm-pyk run kdist --verbose build evm-semantics.plugin `on the `evm-semantics` repo and `poetry run kdist --verbose build -j2 evm-semantics.haskell kontrol.foundry` in the Kontrol repo. The error messages in both leave me inclined to believe that the source for both errors is the same. Attached are the logs for the execution of each command.

[evm-semantics-error.txt](https://github.com/runtimeverification/kontrol/files/14495939/evm-semantics-error.txt)
[kontrol-error.txt](https://github.com/runtimeverification/kontrol/files/14495940/kontrol-error.txt)

Based on parts of the error message and a couple of comments I found in [a stackoverflow post](https://stackoverflow.com/questions/74543715/usr-bin-ld-cannot-find-lstdc-no-such-file-or-directory-on-running-flutte), I could successfully install the `evm-semantics.plugin` and, subsequently, Kontrol once I installed `libstdc++-12-dev`.

Could someone please validate if this is an actual necessary dependency of the project? Or is it a consequence of an eventual particularity of the VM on which I built Kontrol?

**Comment by anvacaru** [comment]
Not sure if it helps, but on `Ubuntu 22.04.4 LTS` I've tried `/sbin/ldconfig -p | grep stdc++` to see what version do I have active and it seems I am running `libstdc++6`.

```sh
anvacaru@desktop cse$ /sbin/ldconfig -p | grep stdc++
        libstdc++.so.6 (libc6,x86-64) => /lib/x86_64-linux-gnu/libstdc++.so.6
        libstdc++.so.6 (libc6) => /lib32/libstdc++.so.6

```

**Comment by ehildenb** [comment]
I believe @qian-hu also had this same issue. @qian-hu is this the same fix?

**Comment by palinatolmach** [comment]
I opened a [small PR](https://github.com/runtimeverification/evm-semantics/pull/2336) adding `libstdc++12-dev` to the list of system dependencies for Ubuntu >= 22.04.
