### ISSUE TITLE
Pull out instrumentation logic for debugTraceTransaction from Firefly

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/kontrol#454]
Part of https://github.com/runtimeverification/kontrol/issues/446.

We should take the `COVERAGE-EVM` module and get it working as a separate `firefly` build in Kontrol, where it instruments KEVM with this inforamtion and builds the LLVM backend with it using Kontrol's build system. That can then be used to implement `debugTraceTransaction` in Kontrol.

**Comment by palinatolmach** [comment]
@yale-vinson @anvacaru I don't think this issue is in progress, is it? Is it related to any engagements?

**Comment by anvacaru** [comment]
I forgot to close this issue after https://github.com/runtimeverification/kontrol/pull/469 got merged.
