### ISSUE TITLE
Add counterexample to interactive KCFG viewer

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#46]
Related: https://github.com/runtimeverification/evm-semantics/pull/1946
Similarly to how we output a counterexample (i.e., concrete assignment to variables) for the failing proof of a Foundry test in runtimeverification/evm-semantics#1927, we should use the `get-model` endpoint introduced in the Haskell backend to show the model of a specific node when `kevm foundry-show  --node` is executed. Consider adding the model to the interactive KCFG viewer.

**Comment by anvacaru** [comment]
We should sepparate counterexamples from the kcfg viewer, as the kcfg viewer is intended to inspect nodes of the proof. I don't see a point to display the counter example for/in each node.
