### ISSUE TITLE
Constraint reordering causes tests to fail

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#533]
As reported by @goodlyrottenapple, removing the sortedness of constraints leads to them getting reordered when running tests locally (as compared to golden files) on Linux, causing tests to fail:

![image](https://github.com/runtimeverification/kontrol/assets/11912158/ff498792-aa73-4118-b423-aed6bf821994)

@PetarMax has suggested to bring back sortedness for constraints, as there seem to be such cross-machine issues. @ehildenb @tothtamas28 would appreciate your feedback!

**Comment by PetarMax** [comment]
I've made a [PR](https://github.com/runtimeverification/k/pull/4281) in `pyk` that reverts the change - @goodlyrottenapple, perhaps you could try and see what happens?

**Comment by tothtamas28** [comment]
Is it possible that this nondeterminism is already present in the backend RPC responses? If so, it would be ideal to fix the issue there. (And until then, do the revert as a hotfix.)

**Comment by goodlyrottenapple** [comment]
After further investigation, I think the issue is likely caused by running a version of booster where the `Ord` instance for internalised terms has changed. This has happened several time over the last few months. Since the Ord instance is auto-generated there is no guarantee that the set of constrains will be returned in the same order and as such it would probably be safer for golden tests to impose an order on the pyk side.

**Comment by PetarMax** [comment]
I wouldn't expect non-determinism, but I would expect a library somewhere to impose an ordering that may vary with versions, e.g., `Ord`, as you observed.

**Comment by tothtamas28** [comment]
> Since the Ord instance is auto-generated there is no guarantee that the set of constrains will be returned in the same order

Is it possible to order constraints based on a custom `Ord` instance before returning the response? That way, the two backends could return terms with constraints always having the same order.

> I wouldn't expect non-determinism

Depends on implementation, e.g. in CPython:

```
$ python -c 'print(*{"foo", "bar", "baz"})'
foo bar baz
$ python -c 'print(*{"foo", "bar", "baz"})'
baz bar foo

**Comment by PetarMax** [comment]
I have the [PR](https://github.com/runtimeverification/k/pull/4281) reverting the change passing all tests in pyk, KEVM, and Kontrol. Changes were needed for some of the expected outputs in Kontrol, but nothing out of the ordinary.
