### ISSUE TITLE
Functions with array arguments give "Unsupported ABI type for method` error

### ISSUE THREAD

**Issue by lucasmt** [runtimeverification/kontrol#55]
The function [`_range_predicate`](https://github.com/runtimeverification/evm-semantics/blob/3f37fc99a9cf2d7adf41fa255a8d4a66674780cf/kevm-pyk/src/kevm_pyk/solc_to_k.py#L418) in `solc_to_k.py` does not support array types. As a result, if we try to `foundry-kompile` a function such as
```
function testArray(address[] memory array) public {
	assert(true);
}
```
that has an array as argument, we get the message `Unsupported ABI type for method TestContract.method_TestContract_testArray_address[], will not generate calldata sugar: address[]`, and no rule of the form
```
rule  ( TestContract . testArray ( ... ) => #abiCallData ( ... ) )
```
is added to `foundry.k`. This makes it so that the function cannot be evaluated during symbolic execution. If we try to run `kevm foundry-prove` on this function, the execution just starts branching on conditions like
```
lengthBytes ( TestContract . testArray ( VV0_array_114b9705:K : address[] ) ) <Int 4
```
without ever stepping into the function.

**Comment by palinatolmach** [comment]
Closed by https://github.com/runtimeverification/kontrol/pull/321.
