### ISSUE TITLE
First simplify the initial state and only then compute it's definedness

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/kontrol#560]
When running a proof, the first request we are submitting to the server is to compute the definedness constraints. It sends the `#Ceil` of the initial state to the `"simplify"` endpoint. Now, Booster does not support `#Ceil`, and will forward the request directly to Kore. Remember, that this is the very first request, and that means the Booster's simplifier have not had a chance to send it to the LLVM backend to compute concrete functions. This means that these concrete function will have to be computed by Kore, including for example the notorious `#computeValidJumpDests`. This is very slow.

We could likely shave a couple of minutes off the runtime of every Kontrol proof by simplifying the initial state without slapping `#Ceil` on it before the call to [assume_defined](https://github.com/runtimeverification/k/blob/_update-deps%2Fruntimeverification%2Fhaskell-backend/pyk/src/pyk/cterm/symbolic.py#L274) in [_method_to_initialized_cfg](https://github.com/runtimeverification/kontrol/blob/808ae0ab008495e6432fde34fcab6b6aabd0944c/src/kontrol/prove.py#L573)

### td;dr

Reorder the first two requests that are made in every proof. First send the initial configuration as is, and then send the  `#Ceil` of the result. This will improve performance.

**Comment by ehildenb** [comment]
This can be done in pyk directly.

Here: https://github.com/runtimeverification/k/blob/f66c8efd33deeb6c97f1a44bf6ff6f6954cdada8/pyk/src/pyk/cterm/symbolic.py#L272

First pass it to `CTermSymbolic.simplify(...)`, then put the `Ceil` on it and pass it to `CTermSymbolic.kast_simplify`.
