### ISSUE TITLE
Explore `vm.dumpState` for external computation

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#629]
There's a new cheatcode that could simplify the current setup for external computation with Kontrol.

The cheatcode, `vm.dumpState($dump_file_path)`, dumps the current state of a Foundry run to a specified file. The format is different from the `vm.stopAndReturnStateDiff()` cheatcode:
```json
{
  "0x5615deb798bb3e4dfa0139dfa1b3d433cc23b72f": {
    "nonce": "0x1",
    "balance": "0x0",
    "code": "0x6080604052348015600f57600080fd5b5060043610603c5760003560e01c80633fb5c1cb1460415780638381f58a146053578063d09de08a14606d575b600080fd5b6051604c3660046083565b600055565b005b605b60005481565b60405190815260200160405180910390f35b6051600080549080607c83609b565b9190505550565b600060208284031215609457600080fd5b5035919050565b60006001820160ba57634e487b7160e01b600052601160045260246000fd5b506001019056fea2646970667358221220091e48831e9eee32d4571d6291233a4fdaaa34b7dced8770f36f5368be825c5264736f6c63430008190033",
    "storage": {
      "0x0000000000000000000000000000000000000000000000000000000000000000": "0x0000000000000000000000000000000000000000000000000000000000000001"
    }
  }
}
```
This format contains only the information we currently use from what is returned via the `vm.stopAndReturnStateDiff()`. Using `vm.dumpState` instead of `vm.stopAndReturnStateDiff()` will save us from un-escaping the produced JSON and filtering which kinds of account access we want to incorporate (for instance, we ignore account accesses with `is_write=false`).
The new JSON structure should simplify the logic for loading the state updates to Kontrol. It also removes the current redundancies, where we'll update a slot three times if it is written three times.

Note that `vm.dumpState` is undocumented at the time of writing.

**Comment by palinatolmach** [comment]
Implemented in https://github.com/runtimeverification/kontrol/pull/657.
