### ISSUE TITLE
Always simplify init node

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/kontrol#67]
Source: https://github.com/runtimeverification/kontrol/pull/63#discussion_r1343171167

Remove this condition: https://github.com/runtimeverification/kontrol/blob/fc4e2287b3699001304f6ba88937ec077a077c04/src/kontrol/prove.py#L306

Also remove corresponding function parameters, e.g.: https://github.com/runtimeverification/kontrol/blob/fc4e2287b3699001304f6ba88937ec077a077c04/src/kontrol/prove.py#L271

As well as the `--no-simplify-init` command-line option: https://github.com/runtimeverification/evm-semantics/blob/7c27cbea9f99aee1773a49b1f729af6eddb66030/kevm-pyk/src/kevm_pyk/cli.py#L221

This issue probably involves updating expected test output.

**Comment by palinatolmach** [comment]
Will be closed by https://github.com/runtimeverification/kontrol/pull/113.
