### ISSUE TITLE
`kontrol prove` option to remove old KCFGs

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#729]
By default, if a new digest of the code is found, Kontrol will keep the previous KCFGs and create a new version of the proofs. However, in the context of KaaS, we might want to delete the old KCFGs.

We should introduce a flag `--remove-old-proofs` to `kontrol prove`, which removes all KCFGs if a new version should be produced.

**Comment by palinatolmach** [comment]
@JuanCoRo shall we close it?

**Comment by JuanCoRo** [comment]
Oh yes, indeed!
