### ISSUE TITLE
Add option to `kontrol clean` to only remove the `proofs` subdirectory

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#740]
PR #735 introduces the logic for removing the outdated `proofs` subdirectory through the `kontrol prove` command. We should make that option accessible to `kontrol clean` as well through a `--old-proofs` option.

**Comment by palinatolmach** [comment]
Has it been closed by https://github.com/runtimeverification/kontrol/pull/755?

**Comment by JuanCoRo** [comment]
Yep! Thanks for pointing it out! :pray:
