### ISSUE TITLE
Adding `--proof-hint` option to `kontrol prove`

### ISSUE THREAD

**Issue by jinxinglim** [runtimeverification/kontrol#752]
### Request

`krun` has an option to Generate proof hint instead of final configuration via the `--proof-hint` option. Can I check if it is possible to add such an option to `kontrol prove` as well?

### Reason

When generating math proof in our Pi2 pipeline, we make use of proof hints that is retrievable from running `krun <some_program> --proof-hint`. We would like to have the same functionality to generate the proof hints when running `kontrol prove` on some tests as well as we want to see how these hints can help us generate proofs of KEVM. 

Note that the proof hints generated will be of binary format instead of normal text format. `krun` provided an option to output the file to a destinated location via `--output-file` option. Perhaps we can output the proof hints into a default output file say `proof.hints` if we are adding this `--proof-hint` option to `kontrol prove`.

### Comment

Let me know if the request is clear. I do not mind working on Kontrol directly and push a PR for you guys to review. But I would need someone to perhaps point me to the location where I can add in this option. Thank you!

CC @xc93 @alexoltean61

**Comment by xc93** [comment]
The request is clear to me. I would also add that we should also add support for both `--proof-hint-instrumentation` and `--proof-hint-instrumentation-slow`, see https://github.com/runtimeverification/llvm-backend/blob/master/docs/proof-trace.md, just in case we need the slow version in the future. 

>  But I would need someone to perhaps point me to the location where I can add in this option.
Do you know who owns `kontrol`?
