### ISSUE TITLE
Reproducible compilation of Foundry projects

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#84]
We seem to be using the older v0.8.13  version of `solc`, which should be updated to 0.8.21 — the latest available version at the moment.

## The problem
Different versions of solidity compiler (`solc`) may generate different EVM bytecode and the proof artefacts such as loop invariants may reference to the bytecode. To make reproducible compilation and proofs,  Kontrol pinpoints to a specific version of solc (0.8.13 as of now). The pinpointed version of solc is installed and linked while installing Kontrol through command `kup install kontrol`. 

By default,  `forge build` command would search the latest version of solidity compiler which is compatible with the solidity source code solidity version pragmas (e.g., `pragma solidity ^0.8.13;`). In order to use the pinpointed solc, Kontrol pass the option `—no-auto-detect` to the `forge build` command (only happens in the nix installation) and foundry does not detect and use a compatible solc version. Instead, it uses the solc resolved through the path environment variable (in nix installation, it resolves to the pinpointed version).  

However, it is highly likely that the pinpointed solc is not compatible with solc version required in customers’ solidity source code. Thus the forge build command would fail. This prevents customer to use the latest version of Kontrol.

### The proposed solution
We shall allow customer to set a solc version for their repo. This can be done by adding the option `solc_version="x.y.z"` to `foundry.toml`. In order to make existing internal tests pass, we can modify the repository by setting the configuration option or make the version as an environment variable to the CI script and the CI script would install and link the specified version of solc. This solution requires that the foundry project can be compiled with only one single version of solc. We shall also have a support matrix tested to allow users to choose the latest version of solc supported by kontrol.

#### Some limitations
1. A project may require multiple versions of solc to compile, i.e., some solidity source files require a version and the other source files require another version. Without the `--no-auto-detect` option, `forge build` would compile the files with different versions and it is even possible that a single file is compiled with multiple versions of solc and thus has multiple output files.  However, `forge build` does not allow setting solc version for each solidity file in the same project. The possible solution is to allow users to set multiple versions of solc, and we have to install the specified versions of solc in a similar way foundry manages multiple versions of solc and specify the `--offline` option to `forge build`.  The installation of multiple solc versions through forge can be achieved by running multiple commands `forge build   --use x.y.z --skip ".sol"`. This command will install the solc version x.y.z without building the project.

2. Installation of Solidity libraries. A foundry project can refer to a remote solidity library such as @openzeppelin and forge-std. However, all the external libraries are managed through forge install/update/remove and the libraries are git repositories and thus have fixed commit hashes. Thus the library build process is deterministic as long as the solc versions are fixed.

**Comment by palinatolmach** [comment]
Related: https://github.com/runtimeverification/evm-semantics/issues/1980, suggests updating the version used in our tests suite to `0.8.19`.

**Comment by F-WRunTime** [comment]
Related to [this Pull Request](https://github.com/runtimeverification/kontrol/pull/105/files) @palinatolmach @spencerhaoxiao Has the issue of running a proof using the nix installation now been resolved such that the pragma header versions are respected and not using a pinned version of solc?

**Comment by spencerhaoxiao** [comment]
[PR 105](https://github.com/runtimeverification/kontrol/pull/105/files) resolves the reproducible compilation problem partially. By default without providing the specific `solc_version` to the `flake.nix` script (`cd kontrol && nix build .`), kontrol relies on the foundry installed by the user (not the one installed with nix). In this case, as long as the user can build their project with `forge build`, kontrol shall build. However, the flag `--no-auto-detect` is not passed to `forge build` and thus does not achieve reproducible compilation objective. 

When kontrol is installed with a version of solc supported by kontrol (e.g., `cd kontrol && nix build .#kontrol.solc_0_8_13`), kontrol uses the foundry and solc installed with nix and passes the flag `--no-auto-detect` to forge build.

**Comment by yale-vinson** [comment]
Closing issue
