### ISSUE TITLE
Good automatization of `kontrol prove` with no arguments

### ISSUE THREAD

**Issue by JuanCoRo** [runtimeverification/kontrol#90]
Similarly to `forge test`, we could have a more complete default behavior for `kontrol prove`. As of now, `kontrol prove` is a no-op.
It would be good if running `kontrol prove` did (at least some of) the following:

- [ ] If a `run-kontrol.sh` script is present, execute `bash run-kontrol.sh 2>&1 | tee log.out`
- [ ] If no `run-kontrol.sh` script is present, then run Kontrol with the default values on all `test`s present in the `.k.sol` files, while recording the output of the runs in a `log.out` file
- [ ] If a configuration mechanism is added similar to that of `foundry.toml`, `kontrol prove` would run with the configuration specified in such file, say `kontrol.toml`

While this might not be a complete description of the things we could add, it's a good starting point.

**Comment by yale-vinson** [comment]
Blocked and will be resolved when PR #373 is merged.

**Comment by palinatolmach** [comment]
Will be partially addressed by TOML file support; for the `run-kontrol.sh`-related improvements, moving it to Backlog for now.
